name: Build and Deploy Documentation

on:
  push:
    branches:
      - beta  # Specify the 'beta' branch here
      # - placeholder

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install devtools
        run: |
          echo "Installing devtools"
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) { stop("Package devtools not found")  }'
        timeout-minutes: 10

      - name: Install roxygen2
        run: |
          echo "Installing roxygen2"
          Rscript -e 'install.packages("roxygen2")'
          Rscript -e 'if (!requireNamespace("roxygen2", quietly = TRUE)) { stop("Package roxygen2 not found") }'
        timeout-minutes: 10

      - name: Install pkgdown
        run: |
          echo "Installing pkgdown"
          Rscript -e 'install.packages("pkgdown")'
        timeout-minutes: 10

      - name: Install remotes
        run: |
          echo "Installing remotes"
          Rscript -e 'install.packages("remotes")'
        timeout-minutes: 10

      - name: Install package dependencies
        run: |
          echo "Installing package dependencies"
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        timeout-minutes: 10
    
      - name: Install data.table
        run: |
          echo "Installing data.table"
          Rscript -e 'install.packages("data.table")'
        timeout-minutes: 10
      - name: Install geosphere
        run: |
          echo "Installing geosphere"
          Rscript -e 'install.packages("geosphere")'
        timeout-minutes: 10
      - name: Install lubridate
        run: |
          echo "Installing lubridate"
          Rscript -e 'install.packages("lubridate")'
        timeout-minutes: 10
      - name: Generate Documentation
        run: |
          echo "Generating documentation"
          Rscript -e 'devtools::document()'
        timeout-minutes: 10

      - name: Build pkgdown site
        run: |
          echo "Building pkgdown site"
          Rscript -e 'pkgdown::build_site()'
        timeout-minutes: 10
      - name: Create new branch for PR
        run: |
          git checkout -b update-branch
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push origin update-branch
      - name: Create Pull Request
        run: |
          gh pr create --title "Automated update PR" --body "This PR was automatically created by GitHub Actions" --base master --head update-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

