name: Build and Deploy Documentation

on:
  push:
    branches:
      - beta  # Specify the 'beta' branch here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('devtools')
          install.packages('roxygen2')
          install.packages('pkgdown')
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)

      - name: Generate Documentation
        run: |
          Rscript -e 'devtools::document()'
      
      - name: Build pkgdown site
        run: |
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

