name: Build and Deploy Documentation

on:
  push:
    branches:
      - beta  # Specify the 'beta' branch here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install devtools
        run: |
          echo "Installing devtools"
          Rscript -e 'install.packages("devtools")'
        timeout-minutes: 10

      - name: Install roxygen2
        run: |
          echo "Installing roxygen2"
          Rscript -e 'install.packages("roxygen2")'
        timeout-minutes: 10

      - name: Install pkgdown
        run: |
          echo "Installing pkgdown"
          Rscript -e 'install.packages("pkgdown")'
        timeout-minutes: 10

      - name: Install remotes
        run: |
          echo "Installing remotes"
          Rscript -e 'install.packages("remotes")'
        timeout-minutes: 10

      - name: Install package dependencies
        run: |
          echo "Installing package dependencies"
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
        timeout-minutes: 10

      - name: Generate Documentation
        run: |
          echo "Generating documentation"
          Rscript -e 'devtools::document()'
        timeout-minutes: 10

      - name: Build pkgdown site
        run: |
          echo "Building pkgdown site"
          Rscript -e 'pkgdown::build_site()'
        timeout-minutes: 10


